### ISSUE TITLE
Dependenices conflict on shapely when install with poetry

### ISSUE THREAD

**Issue by tik65536** [allixender/dggrid4py#8]
Hi @allixender, 
I was trying to upgrade dggrid4py to the lastest version (0.2.8), however, poetry complains on the version of shapely doesn't match with the requirement.  The shapely version of my env is 2.0.2 , and the error prompts that the dggrid4py require shapely >=1.7 and <2.0. 

I have try on a completely new env with nothing install except python, still failed with shapely. Here is the screen shot for installing  dggrid4py==0.2.8 in a clean env.

![Screenshot from 2024-10-28 09-42-01](https://github.com/user-attachments/assets/8a9ff995-08f2-45f0-85d4-a68ab60aead8)

The following screen shot i with shapely 2.0.2 installed before installing dggrid4py.

![Screenshot from 2024-10-28 09-41-02](https://github.com/user-attachments/assets/ab1f6120-5d5e-4b21-b476-e3b915c6ccbf)

Thanks,
Tik

**Comment by allixender** [comment]
The published package still had an old version of my project.toml dependencies:

```toml
[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21"
pandas = "^1.3"
fiona = "^1.8"
shapely = "^1.7"
geopandas = "^0.9"
```

My bad. I'll cut a new release and new package version.
